//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public System.Guid IdAuditoria { get; set; }
        public System.Guid IdAfectado { get; set; }
        public Nullable<System.Guid> IdReferencia { get; set; }
        public System.DateTime FechaAfectacion { get; set; }
        public int IdTipo { get; set; }
        public int IdTabla { get; set; }
        public string Comentario { get; set; }
        public string Usuario { get; set; }
        public string UsuarioPC { get; set; }
        public string UsuarioIP { get; set; }
    }
}
