//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargosMensuales
    {
        public System.Guid IdPrestamo { get; set; }
        public Nullable<System.Guid> IdTipoTransaccion { get; set; }
        public Nullable<System.Guid> IdFrecuencia { get; set; }
        public Nullable<System.Guid> IdMovimiento { get; set; }
        public Nullable<double> Monto { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<System.DateTime> FechaCorte { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<bool> EsActivo { get; set; }
        public string Usuario { get; set; }
        public string DireccionIP { get; set; }
        public string NombrePC { get; set; }
    
        public virtual tMovimientos tMovimientos { get; set; }
    }
}
