//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public Categoria()
        {
            this.Clasificacion = new HashSet<Clasificacion>();
        }
    
        public System.Guid IdCategoria { get; set; }
        public System.Guid IdFactor { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Ponderacion { get; set; }
        public bool EsActivo { get; set; }
    
        public virtual Factor Factor { get; set; }
        public virtual ICollection<Clasificacion> Clasificacion { get; set; }
    }
}
