//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteEvaluacion
    {
        public ClienteEvaluacion()
        {
            this.EvaluacionCategoria = new HashSet<EvaluacionCategoria>();
        }
    
        public System.Guid IdClienteEvaluacion { get; set; }
        public System.Guid IdCliente { get; set; }
        public Nullable<System.Guid> IdUsuario { get; set; }
        public Nullable<System.Guid> IdMetodologia { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Puntaje { get; set; }
        public string NoExpediente { get; set; }
        public string NoCredito { get; set; }
        public Nullable<System.DateTime> FechaHoraEvaluacion { get; set; }
        public bool EsActivo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Usuario { get; set; }
        public string UserPC { get; set; }
        public string UserIP { get; set; }
    
        public virtual Metodologia Metodologia { get; set; }
        public virtual ICollection<EvaluacionCategoria> EvaluacionCategoria { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
