//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.AprobacionInstitucion = new HashSet<AprobacionInstitucion>();
            this.ClienteEvaluacion = new HashSet<ClienteEvaluacion>();
            this.Contacto = new HashSet<Contacto>();
            this.DatosNegocio = new HashSet<DatosNegocio>();
            this.Domicilio = new HashSet<Domicilio>();
            this.ResumenTransaccion = new HashSet<ResumenTransaccion>();
            this.ReferenciaCrediticia = new HashSet<ReferenciaCrediticia>();
            this.tClienteCuenta = new HashSet<tClienteCuenta>();
            this.DetalleCliente = new HashSet<DetalleCliente>();
            this.Referencias = new HashSet<Referencias>();
        }
    
        public System.Guid IdCliente { get; set; }
        public System.Guid IdUsuario { get; set; }
        public System.Guid IdSucursal { get; set; }
        public string NombreCompleto { get; set; }
        public string NoIdentificacion { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<System.Guid> IdPais { get; set; }
        public int EstadoPerfil { get; set; }
        public System.DateTime FechaPerfil { get; set; }
        public string Sexo { get; set; }
        public bool EsActivo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Usuario { get; set; }
        public string UserIP { get; set; }
        public string UserPC { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
    
        public virtual ICollection<AprobacionInstitucion> AprobacionInstitucion { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual ICollection<ClienteEvaluacion> ClienteEvaluacion { get; set; }
        public virtual ICollection<Contacto> Contacto { get; set; }
        public virtual ICollection<DatosNegocio> DatosNegocio { get; set; }
        public virtual ICollection<Domicilio> Domicilio { get; set; }
        public virtual ICollection<ResumenTransaccion> ResumenTransaccion { get; set; }
        public virtual ICollection<ReferenciaCrediticia> ReferenciaCrediticia { get; set; }
        public virtual ICollection<tClienteCuenta> tClienteCuenta { get; set; }
        public virtual ICollection<DetalleCliente> DetalleCliente { get; set; }
        public virtual ICollection<Referencias> Referencias { get; set; }
    }
}
