//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosNegocio
    {
        public DatosNegocio()
        {
            this.DocumentosNegocio = new HashSet<DocumentosNegocio>();
            this.NegocioProveedores = new HashSet<NegocioProveedores>();
        }
    
        public System.Guid IdDatosNegocio { get; set; }
        public System.Guid IdCliente { get; set; }
        public string UbicacionNegocio { get; set; }
        public string Tiempo { get; set; }
        public string TipoNegocio { get; set; }
        public bool EsPropio { get; set; }
        public bool Alquila { get; set; }
        public bool Familiar { get; set; }
        public double IngresoVolumen { get; set; }
        public bool EsActivo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Usuario { get; set; }
        public string UserPC { get; set; }
        public string UserIP { get; set; }
        public Nullable<System.Guid> IdDestinoCredito { get; set; }
    
        public virtual ICollection<DocumentosNegocio> DocumentosNegocio { get; set; }
        public virtual ICollection<NegocioProveedores> NegocioProveedores { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual DestinoCredito DestinoCredito { get; set; }
    }
}
