//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosClienteImp
    {
        public System.Guid IdClienteImp { get; set; }
        public string NoCedula { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string EstadoCivil { get; set; }
        public string TelefonoCliente { get; set; }
        public string Domicilio { get; set; }
        public string Departamento { get; set; }
        public string Casa { get; set; }
        public string TelefonoResidencia { get; set; }
        public Nullable<int> CodigoProfesion { get; set; }
        public string Profesion { get; set; }
        public string NoMiembros { get; set; }
        public string NoDependientes { get; set; }
        public Nullable<int> CodigoTipoNegocio { get; set; }
        public string NombreTipoNegocio { get; set; }
        public string DireccionNegocio { get; set; }
        public string CasaNegocio { get; set; }
        public string Metodologia { get; set; }
        public string NoExpediente { get; set; }
        public Nullable<int> CodigoAgencia { get; set; }
        public Nullable<int> CodigoPromotor { get; set; }
        public string NombrePromotor { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
    }
}
