//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePrestamosClienteImp
    {
        public System.Guid IdDetalleClienteImp { get; set; }
        public string NoCedula { get; set; }
        public string CodigoExpediente { get; set; }
        public string NombreExpediente { get; set; }
        public string NoPrestamo { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public Nullable<double> MontoAprobado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
