//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCliente
    {
        public System.Guid IdDetalleCliente { get; set; }
        public System.Guid IdCliente { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string EstadoCivil { get; set; }
        public System.Guid IdPaisNacimiento { get; set; }
        public string Nacionalidad { get; set; }
        public string Alias { get; set; }
        public string Sexo { get; set; }
        public string Ocupacion { get; set; }
        public Nullable<int> MiembrosFamilia { get; set; }
        public Nullable<double> Ingresos { get; set; }
        public bool EsActivo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Usuario { get; set; }
        public string UserIP { get; set; }
        public string UserPC { get; set; }
        public string Profesion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
