//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosNegocio
    {
        public System.Guid IdDocumentoNegocio { get; set; }
        public string TipoRegistros { get; set; }
        public string Institucion { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public Nullable<System.Guid> IdDatosNegocio { get; set; }
        public bool EsActivo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Usuario { get; set; }
        public string UserPC { get; set; }
        public string UserIP { get; set; }
    
        public virtual DatosNegocio DatosNegocio { get; set; }
    }
}
