//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feriados
    {
        public System.Guid IdFeriado { get; set; }
        public string Departamento { get; set; }
        public string Municipio { get; set; }
        public Nullable<int> Dia { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Anio { get; set; }
        public string Descripcion { get; set; }
    }
}
