//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformacionCheque
    {
        public InformacionCheque()
        {
            this.tMovimientos = new HashSet<tMovimientos>();
        }
    
        public System.Guid IdDetalleCheque { get; set; }
        public string NoCheque { get; set; }
        public string Banco { get; set; }
        public string TipoDocumento { get; set; }
        public string Moneda { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Usuario { get; set; }
        public string DireccionIP { get; set; }
        public string DireccionMAC { get; set; }
    
        public virtual ICollection<tMovimientos> tMovimientos { get; set; }
    }
}
