//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMenu
    {
        public ItemMenu()
        {
            this.ItemMenu1 = new HashSet<ItemMenu>();
            this.ItemRol = new HashSet<ItemRol>();
        }
    
        public System.Guid IdItemMenu { get; set; }
        public Nullable<System.Guid> IdItemMenuPadre { get; set; }
        public string Ruta { get; set; }
        public string Texto { get; set; }
        public string Descripcion { get; set; }
        public bool Visible { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public bool EsActivo { get; set; }
    
        public virtual ICollection<ItemMenu> ItemMenu1 { get; set; }
        public virtual ItemMenu ItemMenu2 { get; set; }
        public virtual ICollection<ItemRol> ItemRol { get; set; }
    }
}
