//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemRol
    {
        public System.Guid IdItemRol { get; set; }
        public System.Guid IdItemMenu { get; set; }
        public System.Guid IdRol { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public bool EsActivo { get; set; }
    
        public virtual ItemMenu ItemMenu { get; set; }
    }
}
