//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatrizCalificacion
    {
        public System.Guid IdMatrizCalificacion { get; set; }
        public string Nombre { get; set; }
        public decimal ValorMin { get; set; }
        public decimal ValorMax { get; set; }
        public int Impacto { get; set; }
        public bool EsActivo { get; set; }
        public string Color { get; set; }
    }
}
