//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metodologia
    {
        public Metodologia()
        {
            this.ClienteEvaluacion = new HashSet<ClienteEvaluacion>();
            this.ResumenTransaccion = new HashSet<ResumenTransaccion>();
        }
    
        public System.Guid IdMetodologia { get; set; }
        public string Nombre { get; set; }
        public bool EsActivo { get; set; }
    
        public virtual ICollection<ClienteEvaluacion> ClienteEvaluacion { get; set; }
        public virtual ICollection<ResumenTransaccion> ResumenTransaccion { get; set; }
    }
}
