//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pais
    {
        public Pais()
        {
            this.Ciudad = new HashSet<Ciudad>();
            this.Cliente = new HashSet<Cliente>();
        }
    
        public System.Guid IdPais { get; set; }
        public string Nombre { get; set; }
        public string Nacionalidad { get; set; }
        public bool EsActivo { get; set; }
    
        public virtual ICollection<Ciudad> Ciudad { get; set; }
        public virtual ICollection<Cliente> Cliente { get; set; }
    }
}
