//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumenTransaccion
    {
        public System.Guid IdTransaccionesInstitucion { get; set; }
        public System.Guid IdCliente { get; set; }
        public System.Guid IdMetodologia { get; set; }
        public string NoPrestamo { get; set; }
        public Nullable<System.DateTime> FechaInicioCredito { get; set; }
        public Nullable<System.DateTime> FechaFinCredito { get; set; }
        public Nullable<decimal> MontoPromedio { get; set; }
        public Nullable<int> MaximoDiasMora { get; set; }
        public string Observaciones { get; set; }
        public bool EsActivo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Usuario { get; set; }
        public string UserPC { get; set; }
        public string UserIP { get; set; }
    
        public virtual Metodologia Metodologia { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
