//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.UsuarioRol = new HashSet<UsuarioRol>();
        }
    
        public System.Guid IdRol { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public bool EsActivo { get; set; }
    
        public virtual ICollection<UsuarioRol> UsuarioRol { get; set; }
    }
}
