//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RutaCobroPrincipal
    {
        public RutaCobroPrincipal()
        {
            this.RutaCobro = new HashSet<RutaCobro>();
        }
    
        public System.Guid IdRutaCobro { get; set; }
        public Nullable<System.Guid> IdColector { get; set; }
        public string Serie { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> Impreso { get; set; }
        public Nullable<bool> Procesado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Usuario { get; set; }
        public string DireccionIP { get; set; }
        public string DireccionPC { get; set; }
    
        public virtual ICollection<RutaCobro> RutaCobro { get; set; }
    }
}
