//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public Sucursal()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public System.Guid IdSucursal { get; set; }
        public System.Guid IdCiudad { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
        public string Direccion { get; set; }
        public bool EsActivo { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
