//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCredito
    {
        public tCredito()
        {
            this.tDetallePago = new HashSet<tDetallePago>();
        }
    
        public System.Guid IdPago { get; set; }
        public Nullable<System.Guid> IdTipoTransaccion { get; set; }
        public Nullable<System.Guid> IdCuenta { get; set; }
        public Nullable<System.Guid> IdMovimiento { get; set; }
        public string Serie { get; set; }
        public string NoReferencia { get; set; }
        public string Recibidode { get; set; }
        public string Concepto { get; set; }
        public Nullable<double> MontoRecibido { get; set; }
        public Nullable<double> MontoPagado { get; set; }
        public Nullable<double> MontoAcreditado { get; set; }
        public Nullable<double> PendienteAcreditar { get; set; }
        public Nullable<double> TipoCambio { get; set; }
        public Nullable<System.DateTime> FechaEfectiva { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaProceso { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Usuario { get; set; }
        public string NombrePC { get; set; }
        public string DireccionIP { get; set; }
    
        public virtual TipoTransaccion TipoTransaccion { get; set; }
        public virtual ICollection<tDetallePago> tDetallePago { get; set; }
    }
}
