//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCuotas
    {
        public tCuotas()
        {
            this.tDetallePago = new HashSet<tDetallePago>();
        }
    
        public System.Guid IdCuota { get; set; }
        public System.Guid IdMovimiento { get; set; }
        public Nullable<System.DateTime> FechaProceso { get; set; }
        public Nullable<System.DateTime> FechaCouta { get; set; }
        public Nullable<System.DateTime> FechaNegociacion { get; set; }
        public Nullable<double> MontoCouta { get; set; }
        public Nullable<double> AbonoCuota { get; set; }
        public Nullable<double> SaldoCouta { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string EstadoCuota { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Usuario { get; set; }
        public string NombrePC { get; set; }
        public string DireccionIP { get; set; }
    
        public virtual tMovimientos tMovimientos { get; set; }
        public virtual ICollection<tDetallePago> tDetallePago { get; set; }
    }
}
