//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDetallePago
    {
        public System.Guid IdDetallePago { get; set; }
        public Nullable<System.Guid> IdPago { get; set; }
        public Nullable<System.Guid> IdCuota { get; set; }
        public Nullable<double> SaldoCuota { get; set; }
        public Nullable<double> AbonoCouta { get; set; }
        public Nullable<double> Mora { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Usuario { get; set; }
        public string NombrePC { get; set; }
        public string DireccionIP { get; set; }
        public Nullable<System.Guid> IdTipoPago { get; set; }
    
        public virtual tCredito tCredito { get; set; }
        public virtual tCuotas tCuotas { get; set; }
    }
}
