//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoTransaccion
    {
        public TipoTransaccion()
        {
            this.TipoTransaccion1 = new HashSet<TipoTransaccion>();
            this.tMovimientos = new HashSet<tMovimientos>();
            this.tCredito = new HashSet<tCredito>();
        }
    
        public System.Guid IdTipoTransaccion { get; set; }
        public Nullable<System.Guid> IdTipoTransaccionHijo { get; set; }
        public string CuentaContable { get; set; }
        public string ContraCuenta { get; set; }
        public string Descripcion { get; set; }
        public string Concepto { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<bool> EsActivo { get; set; }
        public string Usuario { get; set; }
        public string DireccionIP { get; set; }
        public string NombrePC { get; set; }
    
        public virtual ICollection<TipoTransaccion> TipoTransaccion1 { get; set; }
        public virtual TipoTransaccion TipoTransaccion2 { get; set; }
        public virtual ICollection<tMovimientos> tMovimientos { get; set; }
        public virtual ICollection<tCredito> tCredito { get; set; }
    }
}
