//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPlastico
    {
        public tPlastico()
        {
            this.tMovimientos = new HashSet<tMovimientos>();
        }
    
        public System.Guid IdPlastico { get; set; }
        public System.Guid IdCuenta { get; set; }
        public string NoTarjeta { get; set; }
        public string NombrePlastico { get; set; }
        public Nullable<bool> EsActivo { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Usuario { get; set; }
        public string DireccionIP { get; set; }
        public string NombrePC { get; set; }
    
        public virtual tClienteCuenta tClienteCuenta { get; set; }
        public virtual ICollection<tMovimientos> tMovimientos { get; set; }
    }
}
