//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tVehiculos
    {
        public tVehiculos()
        {
            this.tMovimientos = new HashSet<tMovimientos>();
        }
    
        public System.Guid IdVehiculo { get; set; }
        public string Codigo { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Anio { get; set; }
        public string Color { get; set; }
        public string Placa { get; set; }
        public string Chasis { get; set; }
        public string Motor { get; set; }
        public string Circulacion { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Usuario { get; set; }
        public string NombrePC { get; set; }
        public string DireccionIP { get; set; }
    
        public virtual ICollection<tMovimientos> tMovimientos { get; set; }
    }
}
