//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioRol
    {
        public System.Guid IdUsuarioRol { get; set; }
        public Nullable<System.Guid> IdRol { get; set; }
        public Nullable<System.Guid> IdUsuario { get; set; }
        public Nullable<bool> EsActivo { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Usuario { get; set; }
        public string UserIP { get; set; }
        public string UserPC { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
