//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DatosCredito3
    {
        public System.Guid IdMovimiento { get; set; }
        public string NombreCompleto { get; set; }
        public string NoIdentificacion { get; set; }
        public string Descripcion { get; set; }
        public string NoCuenta { get; set; }
        public string NoTarjeta { get; set; }
        public string NoMovimiento { get; set; }
        public Nullable<double> Principal { get; set; }
        public Nullable<double> PlazoMeses { get; set; }
        public Nullable<int> NoCuotas { get; set; }
        public Nullable<System.DateTime> fechadesembolso { get; set; }
        public string fechav { get; set; }
    }
}
