//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDatosNegocio
    {
        public System.Guid IdCliente { get; set; }
        public System.Guid IdDatosNegocio { get; set; }
        public string TipoNegocio { get; set; }
        public string UbicacionNegocio { get; set; }
        public string Tiempo { get; set; }
        public bool Alquila { get; set; }
        public bool EsPropio { get; set; }
        public bool Familiar { get; set; }
        public double IngresoVolumen { get; set; }
        public string DestinoCredito { get; set; }
    }
}
