//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDatosVehiculos
    {
        public System.Guid IdMovimiento { get; set; }
        public string NombreCompleto { get; set; }
        public string NoIdentificacion { get; set; }
        public string Codigo { get; set; }
        public string Marca { get; set; }
        public string Placa { get; set; }
        public Nullable<double> MontoTransaccion { get; set; }
    }
}
