//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDatosGeneralesPerfil
    {
        public System.Guid IdCliente { get; set; }
        public string NombreCompleto { get; set; }
        public string Sexo { get; set; }
        public string NoIdentificacion { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string PaisEmisor { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string EstadoCivil { get; set; }
        public string PaisNacimiento { get; set; }
        public string Nacionalidad { get; set; }
        public string Alias { get; set; }
        public string Profesion { get; set; }
        public string Ocupacion { get; set; }
        public Nullable<int> MiembrosFamilia { get; set; }
        public Nullable<double> Ingresos { get; set; }
        public string Sucursal { get; set; }
    }
}
