//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEvaluacionClienteCategoria
    {
        public System.Guid IdClienteEvaluacion { get; set; }
        public string Factor { get; set; }
        public string Categoria { get; set; }
        public int Puntuacion { get; set; }
        public Nullable<decimal> Ponderacion { get; set; }
        public decimal CalculoRiesgo { get; set; }
    }
}
