//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEvaluacionCliente
    {
        public System.Guid IdClienteEvaluacion { get; set; }
        public string NombreCompleto { get; set; }
        public string NoIdentificacion { get; set; }
        public string Promotor { get; set; }
        public string Codigo { get; set; }
        public string CodigoAgencia { get; set; }
        public string Sucursal { get; set; }
        public string Metodologia { get; set; }
        public Nullable<decimal> Puntaje { get; set; }
        public string NoExpediente { get; set; }
        public string NoCredito { get; set; }
        public Nullable<System.DateTime> FechaHoraEvaluacion { get; set; }
    }
}
