//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPICIngresadosDetallados
    {
        public string Cedula { get; set; }
        public string NombreCompleto { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Sucursal { get; set; }
        public string Promotor { get; set; }
        public int EstadoPerfil { get; set; }
        public string Metodologia { get; set; }
    }
}
