//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReferencias
    {
        public System.Guid IdCliente { get; set; }
        public string Banco { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Plazo { get; set; }
        public string NombreCompleto { get; set; }
        public string NoIdentificacion { get; set; }
        public string Telefono { get; set; }
        public string CentroLaboral { get; set; }
        public string Direccion { get; set; }
    }
}
