//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisSegLT.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwResumenTransacciones
    {
        public System.Guid IdCliente { get; set; }
        public Nullable<int> CantidadPrestamos { get; set; }
        public string Metodologia { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> MaximoDiasMora { get; set; }
    }
}
